[package]
name = "dwebble"
version = "0.1.0"
edition = "2024"

[build-dependencies]
#cbindgen = "0.28.0"
cxx-build = "1.0.158"

[dependencies]
cxx = { version = "1.0.158" }
tokio = "1.44.2"
tonic = "0.13.0"
#cxx-async = { path = "./Modules/cxx-async/cxx-async" }

[lib]
crate-type = ["staticlib"]
