[package]
name = "dwebble"
version = "0.1.0"
edition = "2024"

[build-dependencies]
#cbindgen = "0.28.0"
cxx-build = "*"

[dependencies]
cxx = { version = "*" }
tokio = { version = "*" }
tonic = { version = "*" }
#cxx-async = { path = "./Modules/cxx-async/cxx-async" }

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[lints.clippy]
implicit_return = "deny"
needless_return = "allow"
