[package]
name = "dwebble"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cbindgen = { version = "0.29.0", features = ["default"] }
cxx-build = "*"

[dependencies]
cxx = { version = "*", features = ["std"] }
tokio = { version = "*" }
tonic = { version = "*" }

uuid = { version = "*", features = ["v7"] }
#cxx-async = {version = "*"}

[lib]
crate-type = ["staticlib"]
path = "src/ffi.rs"

[lints.clippy]
implicit_return = "deny"
needless_return = "allow"

[profile.dev.build-override]
debug = true
